### ISSUE TITLE
nextBest: doselimit=0 leads to error

### ISSUE THREAD

**Issue by 0liver0815** [Roche/crmPack#482] opened 2023-01-20 11:02 UTC
It is possible to specify a doselimit of 0 for the `nextBest` method. This leads to an error. Please see the following example.
Some checks may be necessary.

```
# Example of usage for `NextBestMTD` NextBest class.

# Create the data.
my_data <- Data(
  x = c(0.1, 0.5, 1.5, 3, 6, 10, 10, 10),
  y = c(0, 0, 0, 0, 0, 0, 1, 0),
  ID = 1:8,
  cohort = c(0, 1, 2, 3, 4, 5, 5, 5),
  doseGrid = c(0.1, 0.5, 1.5, 3, 6, seq(from = 10, to = 80, by = 2))
)

# Initialize the CRM model used to model the data.
my_model <- LogisticLogNormal(
  mean = c(-0.85, 1),
  cov = matrix(c(1, -0.5, -0.5, 1), nrow = 2),
  ref_dose = 56
)

# Set-up some MCMC parameters and generate samples from the posterior.
my_options <- McmcOptions(burnin = 100, step = 2, samples = 500)
my_samples <- mcmc(my_data, my_model, my_options)

# Define the rule for dose increments and calculate the maximum dose allowed.
my_increments <- IncrementsRelative(
  intervals = c(0, 20),
  increments = c(1, 0.33)
)
next_max_dose <- maxDose(my_increments, data = my_data)

# Define the rule which will be used to select the next best dose
# based on the 'NextBestMTD' class.
mtd_next_best <- NextBestMTD(
  target = 0.33,
  derive = function(mtd_samples) {
    quantile(mtd_samples, probs = 0.25)
  }
)

# Calculate the next best dose.
dose_recommendation <- nextBest(
  nextBest = mtd_next_best,
  doselimit = 0,
  samples = my_samples,
  model = my_model,
  data = my_data
)

dose_recommendation
```

```
$value
numeric(0)

$plot
Error in `check_aesthetics()`:
! Aesthetics must be either length 1 or the same as the data (1): x
Run `rlang::last_error()` to see where the error occurred.
```

**Comment by wwojciech** [comment] 2023-03-21 07:58
Hi @0liver0815, specifying `doselimit = 0` makes no sense to me. It think this should not be allowed, and we can just better handle this rather than waiting for the error (from `ggplot` in this case).
@danielinteractive - what do you think about it?

**Comment by danielinteractive** [comment] 2023-03-21 09:31
@wwojciech we can keep this where it is I think for now. 0 might be produced as an output from some recommendation or max increment etc. rules

**Comment by wwojciech** [comment] 2023-03-21 10:05
> @wwojciech we can keep this where it is I think for now. 0 might be produced as an output from some recommendation or max increment etc. rules

Thanks @danielinteractive, so you would suggest to close this issue for now, leave it open to improve (at some later point) the handling of `doselimit = 0` so that to avoid `ggplot`error?

**Comment by danielinteractive** [comment] 2023-03-21 10:09
let's leave it open for now

**Comment by danielinteractive** [comment] 2023-05-05 07:42
@0liver0815 In https://github.com/Roche/crmPack/blob/main/R/Rules-methods.R#L38 we could check at the generic (so applying to all `nextBest()` methods 
1) that the dose limit is above the minimum of the dose grid, not 0 (tangential to this topic)
2) if the dose limit is identical to the minimum of the dose grid, directly return that minimum, since no additional computations needed?

It seems the bug comes from a plotting problem.

**Comment by dimitriskontosBAY** [comment] 2023-10-31 18:17
I rerun the example code provided by Oliver that initiated this issue in the first place BUT I can not reproduce the error in the plot. Do we still need to procced with the solution suggested by @danielinteractive above?

**Closed** 2023-11-06 06:58 UTC
Labels: bug, discussion
